# Site settings
name: 'Nick and Katie'
description: 'Nick and Katie Travel Blog'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://www.nickpape.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/
theme: minima

author:
    name: 'Nick Pape'
    email: ''
    uri: 'https://github.com/nickpape'

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: false
        disqus: false

plugins:
    - jekyll-feed
    - jekyll-sitemap
